
server:
  port: 8081

spring:
  twse:
    year-interval: 1
  sql:
    init:
      mode: always
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3306/twse # ??????C/user/userName?????
    driver-class-name: com.mysql.cj.jdbc.Driver #??driver
    username: root
    password: root
  jpa:
    database- platform: org.hibernate.dialect.MySQLDialect
#
#
#    hibernate:
mybatis:
  mapper-locations: classpath:mapper/*.xml
#      ddl-auto: update